### ISSUE TITLE
为啥加载网络视频的时候，进度条的时间会从1s直接跳到10s呢

### ISSUE THREAD

**Issue by RaidenLin** [poholo/MCPlayerKit#6]
老哥能留一下联系方式吗，这里有几个问题想咨询一下

**Comment by poholo** [comment]
贴在这里即可，也方便其他用户查询问题

**Comment by RaidenLin** [comment]
> 贴在这里即可，也方便其他用户查询问题

为啥加载网络视频的时候，进度条的时间会从1s直接跳到10s呢

**Comment by RaidenLin** [comment]
> 贴在这里即可，也方便其他用户查询问题


[屏幕录制2020-11-26 下午1.37.30.mov.zip](https://github.com/poholo/MCPlayerKit/files/5600704/2020-11-26.1.37.30.mov.zip)

**Comment by poholo** [comment]
```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t) (3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"#adad#seek");
    [self.playerKit seekSeconds:10];
});
```
MCPlayerGeneralController.m line 108-111 seek测试代码，可以忽略。

**Comment by RaidenLin** [comment]
> ```
> dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t) (3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
>     NSLog(@"#adad#seek");
>     [self.playerKit seekSeconds:10];
> });
> ```
> 
> 
> MCPlayerGeneralController.m line 108-111 seek测试代码，可以忽略。

好的，感谢
